name: GitHub Profile 3D Contribution (PNG)

on:
  schedule:
    - cron: "0 1 * * *"   # tiap hari (beda jam biar ga bentrok)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate 3D Contribution Profile
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: NoctraXHunt

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update 3D contribution profile" || echo "No changes"
          git push
