name: Generate Contribution Snake (GIF)

on:
  schedule:
    - cron: "0 0 * * *"   # tiap hari
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake GIF
        uses: Platane/snk@v3
        with:
          github_user_name: NoctraXHunt
          outputs: |
            dist/github-contribution-grid-snake.gif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Snake GIF
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
